### ISSUE TITLE
Jekyll won't parse frontmatter from outside the source directory

### ISSUE THREAD

**Issue by skroll** [octopress/ink#29]
Not sure if this is a recent change (I just started poking around the new octopress recently), but Jekyll refuses to load yaml frontmatter from anything outside the site source directory. So if a layout exists in a plugin, it won't be processed (and throws an error) such as:

```
Error reading file /home/skroll/src/theme-test/assets/layouts/post.html: No such file or directory @ rb_sysopen - /home/skroll/src/octopress-site-test/home/skroll/src/theme-test/assets/layouts/post.html
```
You can see how it just appended the absolute path to the end of the site's path. Currently it seems Jekyll's layouts use `Jekyll::Site#in_source_dir` to generate the path sent to the yaml parser, which in turn ensures that a path exists within the site path, and won't take absolute paths.

**Comment by fehwalker** [comment]
I suspect this may be a similar issue to #41. There seem to be a [few](https://github.com/octopress/ink/blob/master/lib/octopress-ink/assets/page.rb#L85) [places](https://github.com/octopress/ink/blob/master/lib/octopress-ink/assets/file.rb#L33) where Plugins.custom_dir (which is set to Octopress.site.plugin_manager.plugins_path.first) is prepended with other paths, but it's already a full path.

**Comment by imathis** [comment]
I downloaded the `octopress-theme-jekyll-default` git project and tried out the demo. It worked but I had to make small changes.

### 1. Instead of `assets/config.yml` The site you're testing with needs to have the gem list in the `_config.yml`. For example, to get it to work with the demo, you need in `demo/_config.yml`:

```
gems:
  - octopress-theme-jekyll-default
```

### 2. With that, add this to the `index.html`
```
---
layout: theme:page
---
```

And the Jekyll build will work just fine.
